[package]
name = "hermes-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hermes"
path = "src/main.rs"

[[bin]]
name = "hermesd"
path = "src/hermesd.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hermes-daemon = { path = "../hermes-daemon" }
hermes-protocol = { path = "../hermes-protocol" }
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
